language: python
python:
  - "3.6"
install:
- pip install -r requirements.txt
- pip install coverage
- pip install codecov
script: coverage run run_all_tests.py
after_success:
- codecov -t 36daa772-7865-40e0-8611-f4dd15dcdbb0